# Cloud Build configuration for Google Cloud Run
steps:
  # Build the application
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
  
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'

images:
  - 'gcr.io/$PROJECT_ID/portfolio:$COMMIT_SHA'